from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(1200,800)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #Sidebar Frame
        self.SidebarFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.SidebarFrame.setGeometry(QtCore.QRect(0, -10, 241, 711))
        self.SidebarFrame.setAutoFillBackground(False)
        self.SidebarFrame.setStyleSheet("background-color: #fff;")
        self.SidebarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SidebarFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SidebarFrame.setObjectName("SidebarFrame")

        #Dentica Label
        self.Dentica = QtWidgets.QLabel(parent=self.SidebarFrame)
        self.Dentica.setGeometry(QtCore.QRect(70, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Dentica.setFont(font)
        self.Dentica.setObjectName("Dentica")

        #Sidebar Layout
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.SidebarFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, 70, 251, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Dash_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/Dashboard.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Dash_btn.setIcon(icon)
        self.Dash_btn.setObjectName("Dash_btn")
        self.verticalLayout.addWidget(self.Dash_btn)
        self.Patient_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/Patients.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Patient_btn.setIcon(icon1)
        self.Patient_btn.setObjectName("Patient_btn")
        self.verticalLayout.addWidget(self.Patient_btn)
        self.Apntmnt_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/Appointments.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Apntmnt_btn.setIcon(icon2)
        self.Apntmnt_btn.setObjectName("Apntmnt_btn")
        self.verticalLayout.addWidget(self.Apntmnt_btn)
        self.Bill_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/Billing.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Bill_btn.setIcon(icon3)
        self.Bill_btn.setObjectName("Bill_btn")
        self.verticalLayout.addWidget(self.Bill_btn)
        self.Rep_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/Reports.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.Rep_btn.setIcon(icon4)
        self.Rep_btn.setObjectName("Rep_btn")
        self.verticalLayout.addWidget(self.Rep_btn)
        self.Pages = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.Pages.setGeometry(QtCore.QRect(240, 0, 831, 671))
        self.Pages.setStyleSheet("background: #F8FAFC;")
        self.Pages.setObjectName("Pages")
        self.Dashboard_page = QtWidgets.QWidget()
        self.Dashboard_page.setObjectName("Dashboard_page")
        self.frame = QtWidgets.QFrame(parent=self.Dashboard_page)
        self.frame.setGeometry(QtCore.QRect(0, -10, 991, 71))
        self.frame.setStyleSheet("background-color: #fff;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.not_btn = QtWidgets.QPushButton(parent=self.frame)
        self.not_btn.setGeometry(QtCore.QRect(720, 30, 41, 31))
        self.not_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/new/notifications_24dp_5F6368_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.not_btn.setIcon(icon5)
        self.not_btn.setIconSize(QtCore.QSize(25, 25))
        self.not_btn.setObjectName("not_btn")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 30, 41, 31))
        self.pushButton_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/new/person_24dp_5F6368_FILL0_wght400_GRAD0_opsz24 (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.TotPat_card = QtWidgets.QFrame(parent=self.Dashboard_page)
        self.TotPat_card.setGeometry(QtCore.QRect(20, 90, 181, 101))
        self.TotPat_card.setStyleSheet("background-color: #fff; border-radius: 12px;")
        self.TotPat_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.TotPat_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.TotPat_card.setObjectName("TotPat_card")
        self.label_2 = QtWidgets.QLabel(parent=self.TotPat_card)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.TotPat_card)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.TotApp_card = QtWidgets.QFrame(parent=self.Dashboard_page)
        self.TotApp_card.setGeometry(QtCore.QRect(220, 90, 181, 101))
        self.TotApp_card.setStyleSheet("background-color: #fff; border-radius: 12px;")
        self.TotApp_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.TotApp_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.TotApp_card.setObjectName("TotApp_card")
        self.label_3 = QtWidgets.QLabel(parent=self.TotApp_card)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setToolTipDuration(-7)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.TotApp_card)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.PendPay_card = QtWidgets.QFrame(parent=self.Dashboard_page)
        self.PendPay_card.setGeometry(QtCore.QRect(420, 90, 181, 101))
        self.PendPay_card.setStyleSheet("background-color: #fff; border-radius: 12px;")
        self.PendPay_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.PendPay_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.PendPay_card.setObjectName("PendPay_card")
        self.label_4 = QtWidgets.QLabel(parent=self.PendPay_card)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setToolTipDuration(-7)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.PendPay_card)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ComTreat_card = QtWidgets.QFrame(parent=self.Dashboard_page)
        self.ComTreat_card.setGeometry(QtCore.QRect(620, 90, 181, 101))
        self.ComTreat_card.setStyleSheet("background-color: #fff; border-radius: 12px;")
        self.ComTreat_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ComTreat_card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ComTreat_card.setObjectName("ComTreat_card")
        self.label_8 = QtWidgets.QLabel(parent=self.ComTreat_card)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setToolTipDuration(-7)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.ComTreat_card)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.frame_2 = QtWidgets.QFrame(parent=self.Dashboard_page)
        self.frame_2.setGeometry(QtCore.QRect(30, 210, 591, 461))
        self.frame_2.setStyleSheet("  background: #fff; border-radius: 12px;\n"
"               ")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.UpAp_table = QtWidgets.QTableWidget(parent=self.frame_2)
        self.UpAp_table.setGeometry(QtCore.QRect(40, 80, 521, 361))
        self.UpAp_table.setObjectName("UpAp_table")
        self.UpAp_table.setColumnCount(5)
        self.UpAp_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table.setHorizontalHeaderItem(4, item)
        self.frame_3 = QtWidgets.QFrame(parent=self.Dashboard_page)
        self.frame_3.setGeometry(QtCore.QRect(630, 210, 181, 461))
        self.frame_3.setStyleSheet("  background: #fff; border-radius: 12px;\n"
"               ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(20, 0, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.Pages.addWidget(self.Dashboard_page)
        self.Patients_page = QtWidgets.QWidget()
        self.Patients_page.setObjectName("Patients_page")
        self.frame_4 = QtWidgets.QFrame(parent=self.Patients_page)
        self.frame_4.setGeometry(QtCore.QRect(0, -10, 991, 71))
        self.frame_4.setStyleSheet("background-color: #fff;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(20, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.not_btn_2 = QtWidgets.QPushButton(parent=self.frame_4)
        self.not_btn_2.setGeometry(QtCore.QRect(590, 30, 41, 31))
        self.not_btn_2.setText("")
        self.not_btn_2.setIcon(icon5)
        self.not_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.not_btn_2.setObjectName("not_btn_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 30, 41, 31))
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.search_patient = QtWidgets.QLineEdit(parent=self.frame_4)
        self.search_patient.setGeometry(QtCore.QRect(360, 30, 211, 31))
        self.search_patient.setStyleSheet("background-color: #F1F5F9; border-radius: 8px;")
        self.search_patient.setReadOnly(False)
        self.search_patient.setObjectName("search_patient")
        self.AddPat_btn = QtWidgets.QPushButton(parent=self.frame_4)
        self.AddPat_btn.setGeometry(QtCore.QRect(700, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.AddPat_btn.setFont(font)
        self.AddPat_btn.setStyleSheet("background-color: #3b82f6; border-radius: 8px; color: white;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/new/add_24dp_5F6368_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.AddPat_btn.setIcon(icon7)
        self.AddPat_btn.setObjectName("AddPat_btn")
        self.Pat_table_Frame = QtWidgets.QFrame(parent=self.Patients_page)
        self.Pat_table_Frame.setGeometry(QtCore.QRect(20, 80, 781, 581))
        self.Pat_table_Frame.setStyleSheet("  background: #fff; border-radius: 12px; border: 1px solid #e5e7eb;\n"
"               ")
        self.Pat_table_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Pat_table_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Pat_table_Frame.setObjectName("Pat_table_Frame")
        self.UpAp_table_2 = QtWidgets.QTableWidget(parent=self.Pat_table_Frame)
        self.UpAp_table_2.setGeometry(QtCore.QRect(10, 20, 751, 541))
        self.UpAp_table_2.setObjectName("UpAp_table_2")
        self.UpAp_table_2.setColumnCount(5)
        self.UpAp_table_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_2.setHorizontalHeaderItem(4, item)
        self.Pages.addWidget(self.Patients_page)
        self.Appointments_page = QtWidgets.QWidget()
        self.Appointments_page.setObjectName("Appointments_page")
        self.app_frame = QtWidgets.QFrame(parent=self.Appointments_page)
        self.app_frame.setGeometry(QtCore.QRect(0, -10, 991, 71))
        self.app_frame.setStyleSheet("background-color: #fff;")
        self.app_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.app_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.app_frame.setObjectName("app_frame")
        self.label_13 = QtWidgets.QLabel(parent=self.app_frame)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.not_btn_3 = QtWidgets.QPushButton(parent=self.app_frame)
        self.not_btn_3.setGeometry(QtCore.QRect(550, 30, 41, 31))
        self.not_btn_3.setText("")
        self.not_btn_3.setIcon(icon5)
        self.not_btn_3.setIconSize(QtCore.QSize(25, 25))
        self.not_btn_3.setObjectName("not_btn_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.app_frame)
        self.pushButton_4.setGeometry(QtCore.QRect(600, 30, 41, 31))
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.Search_app = QtWidgets.QLineEdit(parent=self.app_frame)
        self.Search_app.setGeometry(QtCore.QRect(320, 30, 211, 31))
        self.Search_app.setStyleSheet("background-color: #F1F5F9; border-radius: 8px;")
        self.Search_app.setReadOnly(False)
        self.Search_app.setObjectName("Search_app")
        self.AddApp_btn = QtWidgets.QPushButton(parent=self.app_frame)
        self.AddApp_btn.setGeometry(QtCore.QRect(660, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.AddApp_btn.setFont(font)
        self.AddApp_btn.setStyleSheet("background-color: #3b82f6; border-radius: 8px; color: white;")
        self.AddApp_btn.setIcon(icon7)
        self.AddApp_btn.setObjectName("AddApp_btn")
        self.app_table_frame = QtWidgets.QFrame(parent=self.Appointments_page)
        self.app_table_frame.setGeometry(QtCore.QRect(10, 80, 781, 581))
        self.app_table_frame.setStyleSheet("  background: #fff; border-radius: 12px; \n"
"               ")
        self.app_table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.app_table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.app_table_frame.setObjectName("app_table_frame")
        self.UpAp_table_3 = QtWidgets.QTableWidget(parent=self.app_table_frame)
        self.UpAp_table_3.setGeometry(QtCore.QRect(10, 60, 751, 501))
        self.UpAp_table_3.setObjectName("UpAp_table_3")
        self.UpAp_table_3.setColumnCount(5)
        self.UpAp_table_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_3.setHorizontalHeaderItem(4, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.app_table_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.Pages.addWidget(self.Appointments_page)
        self.Billing_page = QtWidgets.QWidget()
        self.Billing_page.setObjectName("Billing_page")
        self.Bill_frame = QtWidgets.QFrame(parent=self.Billing_page)
        self.Bill_frame.setGeometry(QtCore.QRect(0, -10, 991, 71))
        self.Bill_frame.setStyleSheet("background-color: #fff;")
        self.Bill_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Bill_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Bill_frame.setObjectName("Bill_frame")
        self.label_14 = QtWidgets.QLabel(parent=self.Bill_frame)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.not_btn_4 = QtWidgets.QPushButton(parent=self.Bill_frame)
        self.not_btn_4.setGeometry(QtCore.QRect(590, 30, 41, 31))
        self.not_btn_4.setText("")
        self.not_btn_4.setIcon(icon5)
        self.not_btn_4.setIconSize(QtCore.QSize(25, 25))
        self.not_btn_4.setObjectName("not_btn_4")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.Bill_frame)
        self.pushButton_10.setGeometry(QtCore.QRect(640, 30, 41, 31))
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        self.Search_bill = QtWidgets.QLineEdit(parent=self.Bill_frame)
        self.Search_bill.setGeometry(QtCore.QRect(360, 30, 211, 31))
        self.Search_bill.setStyleSheet("background-color: #F1F5F9; border-radius: 8px;")
        self.Search_bill.setReadOnly(False)
        self.Search_bill.setObjectName("Search_bill")
        self.AddBill_btn = QtWidgets.QPushButton(parent=self.Bill_frame)
        self.AddBill_btn.setGeometry(QtCore.QRect(700, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.AddBill_btn.setFont(font)
        self.AddBill_btn.setStyleSheet("background-color: #3b82f6; border-radius: 8px; color: white;")
        self.AddBill_btn.setIcon(icon7)
        self.AddBill_btn.setObjectName("AddBill_btn")
        self.app_table_frame_2 = QtWidgets.QFrame(parent=self.Billing_page)
        self.app_table_frame_2.setGeometry(QtCore.QRect(10, 80, 781, 581))
        self.app_table_frame_2.setStyleSheet("  background: #fff; border-radius: 12px; \n"
"               ")
        self.app_table_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.app_table_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.app_table_frame_2.setObjectName("app_table_frame_2")
        self.UpAp_table_4 = QtWidgets.QTableWidget(parent=self.app_table_frame_2)
        self.UpAp_table_4.setGeometry(QtCore.QRect(10, 60, 751, 501))
        self.UpAp_table_4.setObjectName("UpAp_table_4")
        self.UpAp_table_4.setColumnCount(6)
        self.UpAp_table_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.UpAp_table_4.setHorizontalHeaderItem(5, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.app_table_frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 461, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_2.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_2.addWidget(self.pushButton_15)
        self.Pages.addWidget(self.Billing_page)
        self.Reports_page = QtWidgets.QWidget()
        self.Reports_page.setObjectName("Reports_page")
        self.Bill_frame_2 = QtWidgets.QFrame(parent=self.Reports_page)
        self.Bill_frame_2.setGeometry(QtCore.QRect(0, -10, 991, 71))
        self.Bill_frame_2.setStyleSheet("background-color: #fff;")
        self.Bill_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Bill_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Bill_frame_2.setObjectName("Bill_frame_2")
        self.label_15 = QtWidgets.QLabel(parent=self.Bill_frame_2)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.app_table_frame_3 = QtWidgets.QFrame(parent=self.Reports_page)
        self.app_table_frame_3.setGeometry(QtCore.QRect(20, 70, 781, 581))
        self.app_table_frame_3.setStyleSheet("  background: #fff; border-radius: 12px; \n"
"               ")
        self.app_table_frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.app_table_frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.app_table_frame_3.setObjectName("app_table_frame_3")
        self.Pages.addWidget(self.Reports_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Pages.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Dentica.setText(_translate("MainWindow", "Dentica"))
        self.Dash_btn.setText(_translate("MainWindow", "Dashboard"))
        self.Patient_btn.setText(_translate("MainWindow", "Patients"))
        self.Apntmnt_btn.setText(_translate("MainWindow", "Appointments"))
        self.Bill_btn.setText(_translate("MainWindow", "Billing"))
        self.Rep_btn.setText(_translate("MainWindow", "Reports"))
        self.label.setText(_translate("MainWindow", "Dashboard"))
        self.label_2.setText(_translate("MainWindow", "Total Patient"))
        self.label_5.setText(_translate("MainWindow", "100"))
        self.label_3.setText(_translate("MainWindow", "Today\'s Appointments"))
        self.label_6.setText(_translate("MainWindow", "8"))
        self.label_4.setText(_translate("MainWindow", "Pending Payments"))
        self.label_7.setText(_translate("MainWindow", "12"))
        self.label_8.setText(_translate("MainWindow", "Pending Payments"))
        self.label_9.setText(_translate("MainWindow", "12"))
        self.label_10.setText(_translate("MainWindow", "Upcoming Appointments"))
        item = self.UpAp_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.UpAp_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.UpAp_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.UpAp_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.UpAp_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Notifications</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Patients"))
        self.search_patient.setPlaceholderText(_translate("MainWindow", "Search patients..."))
        self.AddPat_btn.setText(_translate("MainWindow", "Add Patient"))
        item = self.UpAp_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.UpAp_table_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.UpAp_table_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.UpAp_table_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.UpAp_table_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        self.label_13.setText(_translate("MainWindow", "Appointments"))
        self.Search_app.setPlaceholderText(_translate("MainWindow", "Search appointments..."))
        self.AddApp_btn.setText(_translate("MainWindow", "Add Appointments"))
        item = self.UpAp_table_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.UpAp_table_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date & Time"))
        item = self.UpAp_table_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Treatment"))
        item = self.UpAp_table_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.UpAp_table_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        self.pushButton_8.setText(_translate("MainWindow", "All"))
        self.pushButton_9.setText(_translate("MainWindow", "Scheduled"))
        self.pushButton_7.setText(_translate("MainWindow", "Confirmed"))
        self.pushButton_6.setText(_translate("MainWindow", "Waiting"))
        self.label_14.setText(_translate("MainWindow", "Billing"))
        self.Search_bill.setPlaceholderText(_translate("MainWindow", "Search invoices..."))
        self.AddBill_btn.setText(_translate("MainWindow", "New Invoice"))
        item = self.UpAp_table_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.UpAp_table_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date & Time"))
        item = self.UpAp_table_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Treatment"))
        item = self.UpAp_table_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.UpAp_table_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.UpAp_table_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Action"))
        self.pushButton_12.setText(_translate("MainWindow", "All"))
        self.pushButton_13.setText(_translate("MainWindow", "Paid"))
        self.pushButton_14.setText(_translate("MainWindow", "Pending"))
        self.pushButton_15.setText(_translate("MainWindow", "Overdue"))
        self.label_15.setText(_translate("MainWindow", "Reports"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
